name: Feature Request / 功能请求
description: Suggest an idea for this project / 提出一个新功能建议
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a feature! / 感谢您提出功能建议！
        
        Please describe your idea in detail.
        请详细描述您的想法。

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description / 功能描述
      description: A clear and concise description of what you want to happen / 清晰简洁地描述您想要的功能
      placeholder: |
        I would like to be able to...
        我希望能够...
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Problem to Solve / 解决的问题
      description: What problem does this feature solve? / 这个功能解决了什么问题？
      placeholder: |
        This feature would help users to...
        这个功能可以帮助用户...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution / 建议的解决方案
      description: Describe how you would like this feature to work / 描述您希望这个功能如何工作
      placeholder: |
        I think this could be implemented by...
        我认为可以通过...来实现
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered / 备选方案
      description: Describe any alternative solutions or features you've considered / 描述您考虑过的任何备选解决方案或功能

  - type: dropdown
    id: priority
    attributes:
      label: Priority / 优先级
      description: How important is this feature to you? / 这个功能对您有多重要？
      options:
        - Low - Nice to have / 低 - 有了更好
        - Medium - Would be useful / 中 - 会很有用
        - High - Really needed / 高 - 非常需要
        - Critical - Blocking workflow / 紧急 - 阻止工作流程
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Willingness / 贡献意愿
      description: Are you willing to contribute to the implementation of this feature? / 您是否愿意为这个功能的实现做出贡献？
      options:
        - label: I'm willing to submit a Pull Request to implement this feature / 我愿意提交 Pull Request 来实现这个功能
        - label: I can provide testing and feedback / 我可以提供测试和反馈
        - label: I can help with documentation / 我可以协助编写文档

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context / 其他信息
      description: Add any other context or screenshots about the feature request here / 添加任何其他有关功能请求的信息，如截图、示例等
